### ISSUE TITLE
Invalid LiipImagine config in ECommerce

### ISSUE THREAD

**Issue by gorkalaucirica** [LIN3S/PhpDDDStandard#21]
Correct:
```yaml
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../../Ui/Http/Symfony/image"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../../Ui/Http/Symfony"
                cache_prefix: "media/cache"
```
